
def refresh():

    with open("server.py", 'w', newline='') as f:
        f.write("from flask import Flask, render_template, request\n")
        f.write("import csv\n\n")
        f.write("app = Flask(__name__)\n")
        f.write("\n")
        f.write("with open('database.csv', 'r', newline='') as f:\n")
        f.write("    reader = csv.reader(f)\n")
        f.write("    allData = list(reader)\n")
        f.write("    headings = allData[0]\n")
        f.write("    del allData[0]\n")
        f.write("    data =  allData\n")
        f.write("    str_data = str(data)\n")
        f.write("\n")
        f.write("@app.route('/')\n")
        f.write("def index():\n")
        f.write("    return render_template('index.html', data=data, headings=headings)\n")
        f.write("\n")
        f.write("@app.route('/phoneApp', methods=['GET', 'POST'])\n")
        f.write("def parse_request():\n")
        f.write("    if request.method == 'POST':\n")
        f.write("        try:\n")
        f.write("            message = request.form['message']\n")
        f.write("            return save_msg(message)\n")
        f.write("        except:\n")
        f.write('            print("Error with message request")\n')
        f.write("    else:\n")
        f.write("        return str_data, 200, {'Content-Type': 'text/plain; charset=utf-8'}\n")
        f.write("\n")
        f.write("def save_msg(message):\n")
        f.write("    with open('messages.log', 'w') as f:\n")
        f.write("        f.write(message + '\\n')\n")
        f.write("    return 'message saved'\n")
        f.write("\n")
        f.write("if __name__ == '__main__':\n")
        f.write("    app.run(debug=True, port=80, host='0.0.0.0')\n")


